import type { Metadata } from "next";
import { Merriweather_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const geistSans = Merriweather_Sans({
  variable: "--font-merriweather_sans",
  subsets: ["latin", "latin-ext"],
  weight: ['300', '400', '500', '600', '700', '800']
});


export const metadata: Metadata = {
  title: "Astro HR",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>
}>) {

  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <Navbar className="" title=""/>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
